### ISSUE TITLE
Add methods for new API endpoints

### ISSUE THREAD

**Issue by aerni** [aerni/laravel-spotify#10]
There's a couple of new API endpoints, which can be added to this package.

[Episodes API](https://developer.spotify.com/documentation/web-api/reference-beta/#category-episodes)
[Shows API](https://developer.spotify.com/documentation/web-api/reference-beta/#category-shows)

**Comment by boypanjaitan16** [comment]
I just leave my footprint here so I can notice when those important methods is ready for use :)

**Comment by aerni** [comment]
The Episodes and Shows API were added in v1.3.0.
