### ISSUE TITLE
Argument 1 passed to Aerni\Spotify\Normalizer::emptyStringToNull() must be of the type string, null given, called in /home/u6476243/public_html/vendor/aerni/laravel-spotify/src/Spotify.php on line 12 

### ISSUE THREAD

**Issue by boypanjaitan16** [aerni/laravel-spotify#13]
I don't know why, it's work fine in localhost but I get that error when I running it on live server, any ideas ?

**Comment by boypanjaitan16** [comment]
I already tried `use Aerni\Spotify\Facades\SpotifyFacade as Spotify;` and `use Spotify` to use to package but still

**Comment by aerni** [comment]
How does your `.env` file look like? Did you set the correct variables?

**Comment by boypanjaitan16** [comment]
OMG I really forgot that thing, thank you, it's now work fine
