### ISSUE TITLE
/v1/me/

### ISSUE THREAD

**Issue by jeroendev-one** [aerni/laravel-spotify#15]
Hello, is it possible to use the /v1/me/player for e.g? I can't seem to get that working:

    public function mePlayer(): PendingRequest
    {
        $endpoint = '/me/player';
        return new PendingRequest($endpoint);
    }

In the Spotify.php, but it says:

Aerni\Spotify\Exceptions\SpotifyApiException
Invalid username

**Comment by jeroendev-one** [comment]
Would be really cool if this could be implemented!

**Comment by aerni** [comment]
This package only supports endpoints that can be accessed using the [Client Credentials Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow). The `me` endpoint requires a different authentication. There are no plans to implement this as of now, as it would be a major overhaul. I'd like to keep the purpose of this package simple to just access Spotify's public library.

If you need access to the `me` endpoint, I'd suggest you take a look at this package: https://github.com/jwilsson/spotify-web-api-php
