### ISSUE TITLE
Shows End Point

### ISSUE THREAD

**Issue by lewiswilby** [aerni/laravel-spotify#18]
I am currently having some issues connecting to the shows end points.

The error I get is:
Aerni\Spotify\Exceptions\SpotifyApiException  : non existing id

The error itself is incorrect because it actually appears to be an access token related issue (but this is a Spotify API error rather than from the package itself)

If I manually swap out the access token for one which I generate through the authorize page then I can get it to work. It doesn't look like I need a higher level access token but maybe you could help.

**Comment by aerni** [comment]
Is this still an issue? Do any other endpoints work without errors?

**Comment by lewiswilby** [comment]
> Is this still an issue? Do any other endpoints work without errors?

All of the other end points where working fine. I ended up uninstalling the package and writing some custom code to get around this (using the OAuth2/ token refresh method assuming it was related to the token I was receiving)

**Comment by aerni** [comment]
Alright. I can't reproduce the issue. It's working here. If you run into this again, please let me know how to reproduce this issue.

**Comment by jairdeon** [comment]
@lewiswilby, this happened with me. Write your market in spotify.php -> default_config that will souved your problem
