### ISSUE TITLE
Dynamic API Keys

### ISSUE THREAD

**Issue by robman2100** [aerni/laravel-spotify#21]
Is there a way to set api keys based on user? For instance. I can set it in the ENV but I would like to have a more database driven solution on requests. So If somone Logins they can run the requests through their API keys.

**Comment by aerni** [comment]
There's a `SpotifyAuth` class that takes the `clientId` and `clientSecret` to authenticate a user. The binding is done in the [ServiceProvider](https://github.com/aerni/laravel-spotify/blob/master/src/Providers/SpotifyServiceProvider.php). I haven't tested this, but there might be a way to change the binding of that class on a request basis. Check out the [Service Provider documentation](https://laravel.com/docs/master/container).
