### ISSUE TITLE
cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by takielias** [aerni/laravel-spotify#26]
laravel-spotify: 1.2/1.3/1.4
Laravel 7
PHP 7.3
How Can I solve this?

**Comment by aerni** [comment]
This package requires PHP >= 7.4. You're using PHP 7.3. That's probably where your error comes from.

**Comment by takielias** [comment]
> 
> 
> This package requires PHP >= 7.4. You're using PHP 7.3. That's probably where your error comes from.

I also tried PHP 7.4 but the same issue. [This](https://prnt.sc/wd72zu) is the error message  .

**Comment by takielias** [comment]
I have used as `use Aerni\Spotify\Facades\SpotifyClientFacade as Spotify;`

**Comment by takielias** [comment]
Fixed with Wrong facads.
