### ISSUE TITLE
How Can I set Auth Token Manually?

### ISSUE THREAD

**Issue by takielias** [aerni/laravel-spotify#27]
How Can I set Auth Token Manually without using SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET?

**Comment by aerni** [comment]
You can't. This package uses the [Client Credential Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow) for authorization, which requires you to login with your `Client ID` and `Secret Key`.
