### ISSUE TITLE
Gives error after following steps

### ISSUE THREAD

**Issue by ghost** [aerni/laravel-spotify#29]
So I'm using this package: https://github.com/aerni/laravel-spotify for a project, and I've followed the "Usage-steps", but I keep getting this error:

> Non-static method Aerni\Spotify\Spotify::searchTracks() should not be called statically

when I do it the way the package says.

This is my code:

    public function index()
    {
        $variable = Spotify::searchTracks('Wish You Were Here')->get();
        dd($variable);

        return view('pages.index');
    }

with 

> use Aerni\Spotify\Spotify;

on top of the file. Because of the error I tried this:

    (new Spotify)->searchTracks('Wish You Were Here')->get();
but I get this error:

> Too few arguments to function Aerni\Spotify\Spotify::__construct(), 0 passed in C:\ProjectDirectory\hetplatenhuis-newversion\app\Http\Controllers\Pages\IndexController.php on line 13 and exactly 1 expected

**Comment by aerni** [comment]
You're using the wrong class import. Correct is `use Spotify;` at the top of your file.

**Comment by ghost** [comment]
Thanks for your answer!
Then I use the `use Spotify;` import, it gives this error:
> Call to a member function getBody() on null

Any tips? 😅

**Comment by aerni** [comment]
Hmm, no idea. You can also just use the Facade instead of using the Alias. Try `use Aerni\Spotify\Facades\SpotifyFacade`.

**Comment by SabianRobi** [comment]
> Call to a member function getBody() on null

I get the same error, did you find a solution?
