### ISSUE TITLE
Add song to playlist

### ISSUE THREAD

**Issue by BuiltByBucky** [aerni/laravel-spotify#30]
Hi, 
Is there any way to use this wrapper to add songs to a specific user playlist?
I can only see methods to fetch songs from a playlist :( 
Any plans to add this in the future?

**Comment by aerni** [comment]
This feature is not supported. This package only supports endpoints that can be accessed with the Client Credentials Flow. I might add this functionality in the future. But it's a major refactor and I have no plans to add it in the near future.
