### ISSUE TITLE
 "message": "Class 'SpotifyClient' not found"

### ISSUE THREAD

**Issue by Atemndobs** [aerni/laravel-spotify#31]
I looked into the package asswell and in the `vendor/aerni/laravel-spotify/src/SpotifyAuth.php"`
use SpotifyClient , does not exist in this namespace. Instaed there is on ein src/SpotifyClient that extends Client.
I tried swapping both but I cant achieve the expeected results. 
Could you check this please?

by the way, this can be reproduced by exactly follosing the instructions on the install page (Readme).

thanks once more for the great package and I appreaciate your response.

**Comment by aerni** [comment]
What are you trying to do?

**Comment by Atemndobs** [comment]
I am trying to do something as simple as 
Spotify::searchTracks('Closed on Sunday')->get();

Steps to reproduce:
I did the fooling steps as in Installation in Readme, 
 - install per composer
 - Publish config
 - enter my  auth creds and default configs in `config/spotify.php.`
 - Using the `Spotify` wich is actually `SpotifyFacade` from my controller ,
           i tried this. `Spotify::searchTracks('Closed on Sunday')->get();`
Response below:


Specs : Php 7.4, Laravel 7 (based mon  the [Apiato](http://apiato.io/) framework), 

(PS:  I tested this too on a basic laravel 8 project with php 7,4, Same results.

`{
    "message": "Class 'SpotifyClient' not found",
    "exception": "Error",
    "file": "/Users/b.atemkeng/sites/next-song/vendor/aerni/laravel-spotify/src/SpotifyAuth.php",
    "line": 31,
    "trace": [
        {
            "file": "/Users/b.atemkeng/sites/next-song/vendor/aerni/laravel-spotify/src/SpotifyAuth.php",
            "line": 65,
            "function": "generateAccessToken",
            "class": "Aerni\\Spotify\\SpotifyAuth",
            "type": "->"
        },
        {
            "file": "/Users/b.atemkeng/sites/next-song/vendor/aerni/laravel-spotify/src/Providers/SpotifyServiceProvider.php",
            "line": 32,
            "function": "getAccessToken",
            "class": "Aerni\\Spotify\\SpotifyAuth",
            "type": "->"
        },
        {
            "file": "/Users/b.atemkeng/sites/next-song/vendor/laravel/framework/src/Illuminate/Container/Container.php",
            "line": 805,
            "function": "Aerni\\Spotify\\Providers\\{closure}",
            "class": "Aerni\\Spotify\\Providers\\SpotifyServiceProvider",
            "type": "->"
        },
        {
            "file": "/Users/b.atemkeng/sites/next-song/vendor/laravel/framework/src/Illuminate/Container/Container.php",
            "line": 691,
            "function": "build",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "/Users/b.atemkeng/sites/next-song/vendor/laravel/framework/src/Illuminate/Foundation/Application.php",
            "line": 796,
            "function": "resolve",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {`

**Comment by aerni** [comment]
Please try to use either of those two at the top of your file:

```php
// Alias
use Spotify;

// Facade
use Aerni\Spotify\Facades\SpotifyFacade as Spotify;
```

**Comment by Atemndobs** [comment]
Yes that is ok 
But the real problem is the SpotifyClient. 
I don't know how you get it to work without the SpotifyClient.
Do you have any working examples?

**Comment by aerni** [comment]
I just tried on a fresh install and I can't reproduce your issue. There's no need to tinker with the `SpotifyClient`. I don't know what you're trying to do with it. All you have to do to make this package work is to follow the reamde.

1. Install package
2. Publish the config
3. Add your credentials to the `.env`
4. Use the Alias or Facade
5. Start using the API

**Comment by Atemndobs** [comment]
> I just tried on a fresh install and I can't reproduce your issue. There's no need to tinker with the `SpotifyClient`. I don't know what you're trying to do with it. All you have to do to make this package work is to follow the reamde.
> 
> 1. Install package
> 2. Publish the config
> 3. Add your credentials to the `.env`
> 4. Use the Alias or Facade
> 5. Start using the API

**Comment by Atemndobs** [comment]
Ok. I guess Its just a problem with my setup then.
Thanks alot for your support.
