### ISSUE TITLE
Undefined type 'Spotify'.intelephense(1009)

### ISSUE THREAD

**Issue by madfortech** [aerni/laravel-spotify#44]
<?php

namespace App\Http\Controllers;
use Spotify;
use Illuminate\Http\Request;

class SpotifyController extends Controller
{
    public function index(){
        $artistId = 'your-artist-id'; // Replace with the actual artist ID

        $albums = Spotify::artistAlbums($artistId)
            ->includeGroups('album', 'single', 'appears_on', 'compilation')
            ->get();

        // Now you can work with the $albums array

    }
}
![Capture2](https://github.com/aerni/laravel-spotify/assets/21261716/b8e7e300-5ad7-490d-a192-b1b6257b77ee)
this code generate chat gpt and i will try to spotify app data in local host  would you  like to help me solve error why ?

**Comment by aerni** [comment]
I have no idea what you are asking.
