### ISSUE TITLE
Undefined type 'Spotify'.intelephense(1009)

### ISSUE THREAD

**Issue by calypsorrr** [aerni/laravel-spotify#45]
I have the same issue as the last guy. I did everything on the readme file and even asked chatGPT but i still cant use your library becaus it says that Spotify is an undefined type. 

I also tried using this "use Aerni\Spotify\Spotify;" but it also didn't work. 

Do you know whats wrong?

**Comment by aerni** [comment]
How are you importing the class? Both of these examples should work:

```php
use Spotify;
```

```php
use Aerni\Spotify\Facades\SpotifyFacade as Spotify;
```

**Comment by calypsorrr** [comment]
This works: use Aerni\Spotify\Facades\SpotifyFacade as Spotify; 

thank you!

the "use Spotify" didnt work for me

**Comment by aerni** [comment]
Perfect.
