### ISSUE TITLE
Call to a member function getBody() on null

### ISSUE THREAD

**Issue by VeliborSimonovic** [aerni/laravel-spotify#46]
I get this error trying to call SpotifyAuth->getAccessToken();

See code:
    $clientId = config('spotify.auth.client_id');
    $clientSecret = config('spotify.auth.client_secret');
    $spotifyAuth = new SpotifyAuth($clientId, $clientSecret);
    var_dump($spotifyAuth);
        //  $spotifyAuth->getAccessToken();

var_dump gives
object(Aerni\Spotify\SpotifyAuth)#295 (2) { ["clientId":"Aerni\Spotify\SpotifyAuth":private]=> string(32) "XXXXXX" ["clientSecret":"Aerni\Spotify\SpotifyAuth":private]=> string(32) "XXXXXX" }

cliend ID and Secret hidden for obvious reasons.

**Comment by VeliborSimonovic** [comment]
Also I import
use Illuminate\Support\Facades\Route;
use Aerni\Spotify\SpotifyAuth;

**Comment by aerni** [comment]
What's the issue? I don't follow.

Also, why are you using the `SpotifyAuth` class? Just set the Client ID and Client Secret in your `.env` file and use `Aerni\Spotify\Facades\SpotifyFacade`.
