### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by Unleashed2k** [aerni/laravel-spotify#47]
Will this get an update with Laravel 11 support?

Thanks! :)

**Comment by aerni** [comment]
Feel free to create a PR :-)

**Comment by Unleashed2k** [comment]
Done: https://github.com/aerni/laravel-spotify/pull/48

**Comment by kasperhartwich** [comment]
@aerni Will you merge?

**Comment by aerni** [comment]
Will look at this in a couple of weeks. On vacation right now.
