### ISSUE TITLE
Unable to install for laravel 10.10

### ISSUE THREAD

**Issue by awaisamir123** [aerni/laravel-spotify#49]
I am trying to install it for laravel 10.10 and I am unable to install it. Can you please provide solution How I can install it for laravel 10?

**Comment by aerni** [comment]
How are you installing it? What errors do you get?

**Comment by awaisamir123** [comment]
![image](https://github.com/aerni/laravel-spotify/assets/24461610/697354fe-f7c2-4cfb-8693-c12264f3c025)

**Comment by aerni** [comment]
You are trying to install `v2.2.0` which doesn't support Laravel 10. You have to install `v2.1.0`.

**Comment by awaisamir123** [comment]
Working, Thank You.
