### ISSUE TITLE
use Spotify -- Class undefined 

### ISSUE THREAD

**Issue by awaisamir123** [aerni/laravel-spotify#50]
I am facing the issue like class undefined. Even I have installed the package and unable to search this in code base. Can you please tell me how I can make this class?

**Comment by aerni** [comment]
Try this instead:

```php
use Aerni\Spotify\Facades\SpotifyFacade as Spotify;
```

**Comment by awaisamir123** [comment]
![image](https://github.com/aerni/laravel-spotify/assets/24461610/aa9d3ba5-fbe5-454e-831f-f41d757f7a4d)


when I am using this the function is undefined in this name space. I am using LARAVEL 10.10 and package aerni/laravel-spotify 2.1.0

**Comment by aerni** [comment]
This just means that your IDE isn't picking up on the available methods. Did you actually try to see if it works?

**Comment by awaisamir123** [comment]
Yup, seems good. Thank You for your support.
