### ISSUE TITLE
How I can get all tracks with userId?

### ISSUE THREAD

**Issue by awaisamir123** [aerni/laravel-spotify#51]
Hi, I am unable to get all the tracks of a user. How this can be possible to get all tracks by userId?

**Comment by aerni** [comment]
That's not possible. This package only supports endpoints that are accessible with the [Client Credentials Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow).

**Comment by awaisamir123** [comment]
ok, then How I can get the album related to artist. I am unable to pass the query like this

```
  $params = [
            'artist_id'=> $artist,
            'include_groups' => 'album', // or 'single', 'appears_on', 'compilation'
            'country' => 'US', // or any other country code
            'limit' => 10, // Limit the number of albums returned
            'offset' => 0, // Offset for pagination
        ];

        $albums = Spotify::artistAlbums($params);
```

**Comment by awaisamir123** [comment]
I get it.

Things work like this

`       $albums = Spotify::artistAlbums($artist)->offset(0)->limit(10)->get();`

**Comment by awaisamir123** [comment]
Now this showing the bad request

`        $albums = Spotify::artistAlbums($artist)->includeGroups('album, single, appears_on, compilation')->offset(0)->limit(10)->get();
`
