### ISSUE TITLE
Method can't call statically

### ISSUE THREAD

**Issue by boypanjaitan16** [aerni/laravel-spotify#9]
I tried to do as your documentation but i got error
`Non-static method Aerni\Spotify\Spotify::featuredPlaylists() should not be called statically`

And I also tried to call non statically like `new Spotify()` but the constructor need 1 parameter and I don't know what to pass as parameter in constructor.

Any help?

**Comment by aerni** [comment]
How do the imports at the top of your file look like? You have to either import the Alias or the Facade.

```php
// Alias
use Spotify;

// Facade
use Aerni\Spotify\Facades\SpotifyFacade as Spotify;
```

**Comment by boypanjaitan16** [comment]
thanks, this one works `use Aerni\Spotify\Facades\SpotifyFacade as Spotify;`

**Comment by boypanjaitan16** [comment]
one more thing, I didn't see anything about podcast in your doc, is it not available yet ? or ?

**Comment by aerni** [comment]
There was no such endpoint when I created this package. I see that there's now a [Shows](https://developer.spotify.com/documentation/web-api/reference-beta/#category-shows) and [Episodes](https://developer.spotify.com/documentation/web-api/reference-beta/#category-episodes) API. I suppose that's for podcasts. Will be looking into this in the future.

**Comment by boypanjaitan16** [comment]
thank you, I really look into this
